### ISSUE TITLE
CC006 | Unrecognized tokens in condition

### ISSUE THREAD

**Issue by apetrosian** [apigee/apigeelint#107]
Conditions should not have unrecognized tokens (e. g. `{`, `}`).

This rule should return error code.

**Comment by DinoChiesa** [comment]
I suppose we're considering something like this: 
```
  <Condition> proxy.pathsuffix = {something}</Condition>
```
But I am unsure.

Do we have further details on what is imagined here?  Do we still need this kind of check?

**Comment by DinoChiesa** [comment]
Closing this one as ill-defined, not interesting at the moment.
