### ISSUE TITLE
Way to skip the 3rd party javascripts used

### ISSUE THREAD

**Issue by maloosatyam** [apigee/apigeelint#118]
It would be nice if we can provide a list of 3rd party javascript files to be excluded from the lint.

**Comment by DinoChiesa** [comment]
This is possible today. 

The PO013 plugin runs the jshint tool to lint the JS code within a proxy.  If you would like jshint to ignore specific .JS files within the project, drop a file named `.jshintignore` in the directory containing the JS files (/apiproxy/resources/jsc). Within that `.jshintignore` file, include the name of each file to exclude from the lint, on a separate line.
