### ISSUE TITLE
Linter tries to upload bundle to apigee by default

### ISSUE THREAD

**Issue by smolnikov** [apigee/apigeelint#120]
Seems that linter tries to upload bundle here https://github.com/apigeecs/bundle-linter/blob/master/lib/package/bundleLinter.js#L103
If `apiUpload` option is not set up properly, private bundle which is linted might be uploaded to `csdata` organization. This might cause critical security issues.

**Comment by apetrosian** [comment]
Seems like it's not documented feature. I agree that default `destPath` should be removed.

Meanwhile, it will not upload anything unless you specify `config.apiUpload`.
