### ISSUE TITLE
Search from -s/ --path entry point for all apiproxy folders which denote the root of a bundle configuration

### ISSUE THREAD

**Issue by davidwallen** [apigee/apigeelint#122]
Allow for multiple bundles to be linted from one call.

**Comment by davidwallen** [comment]
Giving this one back to the backlog.

**Comment by dpashkevich** [comment]
This would be great in tandem with Apigee's latest [local development setup](https://cloud.google.com/apigee/docs/api-platform/local-development/overview)

**Comment by DinoChiesa** [comment]
Unless there is some great outcry for this, I think we won't implement this. It's already pretty easy to do something similar (better?) with find / xargs: 

```
find ~/dev/apiproxies -type d -name apiproxy -mtime -24 | xargs -n 1 -t apigeelint -f table.js --profile apigeex -e TD002 -s 
```
