### ISSUE TITLE
Support for Shared Flows

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeelint#130]
Tool should be able to detect apiproxy or sharedflowbundle.

**Comment by dwvd** [comment]
Any Tentative date by when support for shared flow  will be available.

**Comment by dwvd** [comment]
@apetrosian @ssvaidyanathan Any Tentative date by when support for shared flow will be available?

**Comment by apetrosian** [comment]
@dwvd we are targeting this feature for [milestone/1](https://github.com/apigeecs/bundle-linter/milestone/1)

**Comment by dwvd** [comment]
@apetrosian @ssvaidyanathan Created pull request for sharedflow linting.

**Comment by cleisommais** [comment]
Hi guys, any news for this support? Anyway, I'd like to help on it. @apetrosian @ssvaidyanathan @kurtkanaskie can you send me any info for help me to finish this new feature?

**Comment by apetrosian** [comment]
Covered in #149 

Hi @cleisommais, thanks for reminder. This will be released in `0.4.0` later today.
