### ISSUE TITLE
Exclude folders and files (JSHint)

### ISSUE THREAD

**Issue by jfernandeze** [apigee/apigeelint#144]
Hi

I'm trying to ignoring file js but It was impossible. i'm trying to put `.jshintignore `or for example use:

```
// Code here will be linted with JSHint.
/* jshint ignore:start */
// Code here will be ignored by JSHint.
/* jshint ignore:end */
```

None of the above has worked

**Comment by DinoChiesa** [comment]
PR #233 will add support for .jshintignore; sorry about the delay! I hadn't seen this issue until now.
