### ISSUE TITLE
PD003 seems doesn't work

### ISSUE THREAD

**Issue by sunil001repo** [apigee/apigeelint#147]
Is emptyRouteRuleLast.js plugin works? I am checking by providing route rule without condition which is not last.

I see issue on line 22 :

if (c.getExpression === "") {  --- This comes undefined as condition itself is not there so if you perform getExpression on that it gives undefined.

any suggestion?

**Comment by kurtkanaskie** [comment]
Good catch, fix is to change:
    var c = routeRules[i].getCondition() || "";
    if (c.getExpression === "") {
to use:
    var c = routeRules[i].getCondition();
    if (!c || c.getExpression === "") {

**Comment by ssvaidyanathan** [comment]
Fixed in. v0.4.9
