### ISSUE TITLE
Rule BN005 gives false warnings for shared flows

### ISSUE THREAD

**Issue by aaldredge** [apigee/apigeelint#151]
Running apigeelint 0.4.0 against a shared flow gives false warnings on rule BN005. 

For example, even though a policy is referenced in a step in the sharedflowbundle/sharedflow/default.xml, running` apigeelint -s sharedflowbundle `generates a warning for each policy saying `<policyname> is not attached to a Step in the bundle.  Remove unused policies. `

**Comment by dougbSlalom** [comment]
I opened a pr to fix this issue https://github.com/apigee/apigeelint/pull/152

**Comment by DinoChiesa** [comment]
This ticket should be closed, marked fixed.
