### ISSUE TITLE
Under checkBundleStructure.js under we need to add yaml also as a valid extension for openapi.

### ISSUE THREAD

**Issue by VenkatVeldurthy** [apigee/apigeelint#166]
Under checkBundleStructure.js, bundleStructure function resources/openapi files/extensions, we also need yaml as a valid extension, other than json. As we have a yaml it is throwing an error.

**Comment by VenkatVeldurthy** [comment]
@kurtkanaskie , yaml is also a valid extension, or do you want me to write my own plugin for that?

**Comment by ssvaidyanathan** [comment]
Fixed in. v0.4.9
