### ISSUE TITLE
Quota policy attachment count does not consider scope of flows

### ISSUE THREAD

**Issue by karsten-wagner** [apigee/apigeelint#168]
Rule PO023 checks how often a quota policy is attached in the proxy.
I have a setup with three different proxy sections/files, each using the same quota in 5 mutually exclusive flows.
The rule simply counts all of them (so 15 in total) and raises an error that it's attached more than once.

Neither three different scopes, nor the mutually exclusive flow setup has been considered - so this creates a false positive.

**Comment by karsten-wagner** [comment]
Recently it turns out this behavior also applies when multiple targets exist. We are using the same quota policy in two different targets within the same proxy and the rule complains the quota is used twice...

Similar to flows, targets are mutually exclusive in the routing, hence apigeelint should not consider the quota to be used twice.

**Comment by samcrutt9900** [comment]
I am facing the same issue with this rule.

**Comment by ssvaidyanathan** [comment]
@karsten-wagner  / @samcrutt9900 - Released v2.36.0 with a fix for this. Can you please try it out?
It looks for the policy and checks if its across flows or across ProxyEndpoint or TargetEndpoint
If its within the same flow, it checks if the Condition tag is same.

**Comment by karsten-wagner** [comment]
@ssvaidyanathan, I can confirm it works now as expected. Thanks for the fix!

**Comment by samcrutt9900** [comment]
I can also confirm it is now working as expected. Thanks for the fix :)
