### ISSUE TITLE
PO007: Raise Fault should allow "raise" prefix

### ISSUE THREAD

**Issue by karsten-wagner** [apigee/apigeelint#177]
I am seeing the following warning generated for my proxy:
´´´text
Policy "Raise Fault 'Invalid Client Secret'" of type "RaiseFault" should have an indicative prefix. Typical prefixes include: ["raisefault","rf","fault"]
´´´
I believe the typical prefix "raise" should be allowed as well, without writing the full "raisefault"...

**Comment by ssvaidyanathan** [comment]
Fixed in v0.5.0

**Comment by karsten-wagner** [comment]
Thank you @ssvaidyanathan !
