### ISSUE TITLE
PO027 - error filename

### ISSUE THREAD

**Issue by Tibeno88** [apigee/apigeelint#216]
Hello,

ApigeeLint @2.1.0
![image](https://user-images.githubusercontent.com/24879275/98349713-a5554700-201a-11eb-8d0f-2e5b60a0c117.png)

on the version, the file describing the hmac plugin does not respect the naming rule.
[myUtil.js](https://github.com/apigee/apigeelint/blob/cdf5cf913eff2451f94751b19b7990b1a51dee9b/lib/package/myUtil.js#L104)

**Update filename to :** 
PO027-hmacPolicy.js

**Comment by kusumikaghosh** [comment]
Hello, 

I am experiencing the same issue. In fact, I think its affecting the previous versions of the module as well.
I have implemented this npm module as part of our CICD pipeline to propagate the Apigee proxy to higher environments. I tried installing a stable previous version and went back until apigeelint@0.4.4, I have the same issue even there. 

Error: /lib/node_modules/apigeelint/lib/package/plugins/po027-hmacPolicy.js, bad plugin filename format

Would be great if you can suggest me a timeline or a workaround.

Thanks,
Kusumika

**Comment by kurtkanaskie** [comment]
Fixed in PR: Renamed po027-hmacPolicy.js to proper convention PO027-hmacPolicy.js #219

**Comment by ssvaidyanathan** [comment]
v2.1.1 released and should have the fix
