### ISSUE TITLE
For plugin file C, bad plugin filename format 2.1.x

### ISSUE THREAD

**Issue by Kittiman** [apigee/apigeelint#221]
We have started to get the following error message starting from release 2.1.x
**For plugin file C, bad plugin filename format**
If running 2.0.0 every thing still working fine.

We are running.
```
npm install -g apigeelint  
apigeelint -s ./src/gateway/apiproxy/

```
if running 
```
npm install -g apigeelint@2.0.0
apigeelint -s ./src/gateway/apiproxy/
```
everything works fine.

**Comment by SavvySkylark** [comment]
I am also seeing this issue.

**Comment by ssvaidyanathan** [comment]
Can you try 2.1.1 please ?

**Comment by Kittiman** [comment]
I did try out the version 2.1.1 this morning with same issue.

**Comment by ssvaidyanathan** [comment]
I just ran it on my sample proxy, it works fine for me. 

Can you share the output?

**Comment by Kittiman** [comment]
I just get this.
**For plugin file C, bad plugin filename format**

**Comment by ssvaidyanathan** [comment]
With the latest version (2.1.x), there is a naming convention for the files

The code expects a format like "XX###-wordsGoHere.js",  e.g. EX007-NamingConventions.js
Can you check if you have any files that does not follow this convention ?

**Comment by Kittiman** [comment]
I have just downloaded apigeelint with npm not extra plugin (js).

Regards

/Johan
________________________________
Från: Sai Saran Vaidyanathan <notifications@github.com>
Skickat: Tuesday, November 10, 2020 5:29:17 PM
Till: apigee/apigeelint <apigeelint@noreply.github.com>
Kopia: Kittiman <kitti@hotmail.se>; Author <author@noreply.github.com>
Ämne: Re: [apigee/apigeelint] For plugin file C, bad plugin filename format 2.1.x (#221)


With the latest version (2.1.x), there is a naming convention for the files

The code expects a format like "XX###-wordsGoHere.js", e.g. EX007-NamingConventions.js
Can you check if you have any files that does not follow this convention ?

**Comment by kurtkanaskie** [comment]
I'm thinking this may be related to Windows and the use of "C:" in the path.

**Comment by Kittiman** [comment]
We have the same problem when running this in Azure DevOps where we use a build agent.
We never make use of C: just only relative path.

Regards

/Johan
________________________________
Från: Kurt Kanaskie <notifications@github.com>
Skickat: Tuesday, November 10, 2020 8:32:04 PM
Till: apigee/apigeelint <apigeelint@noreply.github.com>
Kopia: Kittiman <kitti@hotmail.se>; Author <author@noreply.github.com>
Ämne: Re: [apigee/apigeelint] For plugin file C, bad plugin filename format 2.1.x (#221)


I'm thinking this may be related to Windows and the use of "C:" in the path.

**Comment by kurtkanaskie** [comment]
Looking at myUtils.js getRuleId function, its doing something tricky to get the filename, on my Mac it returns the full path as:
/Users/kurtkanaskie/work/apigee/apigeelint/lib/package/plugins/TD003-targetNameAttr.js:14:40
Then it does a split using ':' to get the filepath without the trailing numbers, that's the bug on Windows.

![image](https://user-images.githubusercontent.com/16242090/98725856-b0361180-2363-11eb-8010-df166bdccf38.png)

**Comment by kurtkanaskie** [comment]
OK, I was able to reproduce in Azure DevOps and just as suspected the "frame" value is:
"at Object.<anonymous> (D:\a\1\s\lib\package\plugins\BN001-checkBundleStructure.js:23:40)"
which fails the filename regex on line 103 above.
Should be able to have a fix later today.

**Comment by ssvaidyanathan** [comment]
v2.1.2 has a fix. Please try and let us know. Once you confirm, will close the issue or please feel free to close the issue

**Comment by Kittiman** [comment]
I have verified and all is back to normal now, thanks!
