### ISSUE TITLE
document and test the export-bundle-unzip-and-then-lint feature

### ISSUE THREAD

**Issue by DinoChiesa** [apigee/apigeelint#228]
- verify and if necessary implement the correct behavior
- implement tests
- update the README appropriately

**Comment by jhd235** [comment]
Hi @DinoChiesa. I'm using apigeelint & like it a lot. Would you be so kind to suggest to me how can I contribute my spare time to the project? E.g. how can I help with this issue?
thanks, 
best regards, Yermek

**Comment by ssvaidyanathan** [comment]
@jhd235 - Thanks a lot for showing interest.

You can contribute by picking the open issues in the repo. Just make sure you assign it to yourself when you pick it so that others are not working on it. 
If you see any gaps or features that could be added, feel free to create an issue and submit a PR

@DinoChiesa - pls add on if I missed any

**Comment by DinoChiesa** [comment]
Circling back on this issue in the backlog.

We _could_ do this work if it would make many lives much simpler. 

But I am not sure we need to implement this, as it's already pretty easy by combining other existing command-line tools with apigeelint.

```
PROXYNAME=whatever
ORG=yourorg
REV=5
OUTDIR=$(mktemp -d /tmp/apigeelint-example.XXXXXX)
curl -s -H "Authorization: Bearer $TOKEN" -X GET \
    "https://apigee.googleapis.com/v1/organizations/$ORG/apis/$PROXYNAME/revisions/$REV?format=bundle" --output $OUTDIR/$PROXYNAME-$REV.zip
unzip $OUTDIR/$PROXYNAME-$REV.zip -d $OUTDIR/$PROXYNAME-$REV-unzipped
apigeelint -f table.js --profile apigeex -s $OUTDIR/$PROXYNAME-$REV-unzipped/apiproxy
```

WDYT?

**Comment by ssvaidyanathan** [comment]
or use [apigeecli export](https://github.com/apigee/apigeecli/blob/main/docs/apigeecli_apis_export.md) available as part of [apigeecli](https://github.com/apigee/apigeecli)

**Comment by DinoChiesa** [comment]
Yes. And be careful with apigeecli export.  It exports ALL APIs!
If you want to export and analyze just ONE apiproxy, then you can use apigeecli fetch.

**Comment by ssvaidyanathan** [comment]
Yes - thats right! Use fetch

**Comment by DinoChiesa** [comment]
```
cliout=($(apigeecli apis fetch -n "$proxyname" --token "$APIGEE_TOKEN" --org "$APIGEE_PROJECT"))
zipname=${cliout[1]}
pair=(${zipname//./ })
shortpname=${pair[0]}
outdir=${shortpname}-unzipped
unzip ${zipname} -d ${outdir}
$apigeelint -f table.js --profile apigeex -s ${outdir}/apiproxy
```

**Comment by DinoChiesa** [comment]
or here: 
https://gist.github.com/DinoChiesa/d9b3714f983e99aa8e3d0c6f27ba2aec
