### ISSUE TITLE
TD002 not applicable for microgateway aware proxies

### ISSUE THREAD

**Issue by karsten-wagner** [apigee/apigeelint#232]
When linting a microgateway aware proxy I receive warning TD002, which asks me to use a target server instead of an URL. This is not applicable for microgateway aware proxies, who need to use a URL by design.

From <https://docs.apigee.com/api-platform/microgateway/3.1.5/setting-and-configuring-edge-microgateway#part2createentitiesonapigeeedge-1createanedgemicrogatewayawareapiproxyonedge>:

> Note: Edge Microgateway-aware proxies must point to an HTTP target endpoint. In other words, the TargetEndpoint for the proxy must include an HTTPTargetConnection. Edge Microgateway is not designed to work with proxies that use either the ScriptTarget or LocalTargetConnection element. ScriptTarget is used to specify Node.js target applications and LocalTargetConnection is used for proxy chaining.

I'd recommend to update this rule not to fire in case the proxy name starts with "edgemicro_".
I am aware how to exclude the rule from the linting process, but I think it would still be feasible to update the rule to work as per Apigee design principles in all cases - not only for cloud proxies...

**Comment by ssvaidyanathan** [comment]
Released in v2.5.0
