### ISSUE TITLE
BN001: OAS folder throwing unexpected folder found error

### ISSUE THREAD

**Issue by mazma26** [apigee/apigeelint#246]
OAS folder used in the OASValidation policy is not being recognised as a valid folder.

https://cloud.google.com/apigee/docs/api-platform/reference/policies/oas-validation-policy

/resources/oas is the only valid folder for this policy. Attempting to point to openapi folder throws deployment errors.

**Comment by ssvaidyanathan** [comment]
Released in v2.5.0
