### ISSUE TITLE
BN001 | Error: Unexpected folder found "xsd" 

### ISSUE THREAD

**Issue by k1mperial** [apigee/apigeelint#258]
But xsd folder required if configuring using SOAPMessageValidation policy to validate XML message against their XSD schemas. It should be in the list of allowed folders
https://docs.apigee.com/api-platform/reference/policies/message-validation-policy

**Comment by DinoChiesa** [comment]
Hmmm that's a good point. Let me look into this.

**Comment by ssvaidyanathan** [comment]
v2.6.0 has the fix

**Comment by k1mperial** [comment]
thanks!
