### ISSUE TITLE
Question about PO001, PO002, PO003, PO004 and PO005 rules

### ISSUE THREAD

**Issue by jcmellado** [apigee/apigeelint#264]
This is not really an issue, just a question about <s>policies</s> rules PO001, PO002, PO003, PO004 and PO005.

Al them have the following description: "A check for a body element must be performed before policy execution."

Why is it necessary to check if the body element is present? Is it about optimization? or just best practices that we ignore?

How should the condition be written? like [the one](https://github.com/apigee/apigeelint/blob/master/test/specs/testthreatProtectionXMLConditionCheck.js#L245) used for testing?

**Comment by ssvaidyanathan** [comment]
@jcmellado - Its more of a best practice and also to improve your security. You don't want attackers to send requests with huge payloads. This can impact your backends and services. These content protection policies help your backend. Hence we added those policies to warn when the proxy takes a request body.

Thanks for reaching out and asking this. However, I would recommend you to use [Apigee community](https://community.apigee.com) to ask such questions. You will get more perspectives and responses from other users as its meant for such discussions.

**Comment by jcmellado** [comment]
Thanks @ssvaidyanathan 

But I'm not asking about the "JSON Threat Protection", "XML Threat Protection", ... **policies**, I'm asking about the "PO001", "PO002", ... **rules**

Sorry, I don't use the correct term. I will edit the question.

**Comment by ssvaidyanathan** [comment]
Got it. Those rules are just there for best practice. Since these policies are usually executed on the request content or the response content, you need to execute this only if there is one else its better to just skip it.
