### ISSUE TITLE
Security Alert for xmldom <= 0.6.0

### ISSUE THREAD

**Issue by tmartinbankunited** [apigee/apigeelint#266]
[GHSA-5fg8-2547-mr8q](https://github.com/advisories/GHSA-5fg8-2547-mr8q)
moderate severity
Vulnerable versions: <= 0.6.0
Patched version: No fix
Impact
xmldom versions 0.6.0 and older do not correctly escape special characters when serializing elements removed from their ancestor. This may lead to unexpected syntactic changes during XML processing in some downstream applications.

Patches
Update to one of the fixed versions of @xmldom/xmldom (^0.5.1 || ^0.6.1 || >=0.7.0). ❗ Users of xmldom should switch to @xmldom/xmldom to not be affected by this vulnerability.

See issue #271 for the status of publishing xmldom to npm or join #270 for Q&A/discussion until it's resolved.

Workarounds
Downstream applications can validate the input and reject the maliciously crafted documents.

References
Similar to this one reported on the Go standard library:

https://mattermost.com/blog/coordinated-disclosure-go-xml-vulnerabilities/
https://mattermost.com/blog/securing-xml-implementations-across-the-web/
For more information
If you have any questions or comments about this advisory:

Open an issue in xmldom/xmldom
Email us: send an email to all addresses that are shown by npm owner ls @xmldom/xmldom

**Comment by ssvaidyanathan** [comment]
Fixed in v2.9.0
