### ISSUE TITLE
onDefaultFaultRule - while getting defaultFaultRules count from the endpoints(proxy and target) - it is adding up the count exponentially

### ISSUE THREAD

**Issue by jampaninc** [apigee/apigeelint#268]

**Comment by DinoChiesa** [comment]
Can you elaborate on what you mean here?  Maybe provide an example API proxy, and snip of some output that shows what you're seeing?  and a description of what you think you should be seeing?  I'm not clear on the meaning of "adding up the count exponentially."

**Comment by ssvaidyanathan** [comment]
Fixed and released in v2.10.0
