### ISSUE TITLE
Install issue, version 2.13.0 

### ISSUE THREAD

**Issue by morten-nielsen** [apigee/apigeelint#291]
We have start seeing an issue on our build pipeline with version 2.13.0.

npm install apigeelint@2.13.0 -g
........
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ([ ! -f package-lock.json ] && npm install --package-lock-only --ignore-scripts --no-audit); npx npm-force-resolutions
npm ERR! npx was unexpected at this time.

![image](https://user-images.githubusercontent.com/28894879/145558955-5ce39cbd-1ae9-4502-b8ef-a86d67ce8261.png)

**Comment by ahemanna** [comment]
I see this error too when I tried to update to latest version. However I was able to install 2.12.0 fine.

**Comment by ssvaidyanathan** [comment]
@DinoChiesa - Can you please take a look. This is after our last push

**Comment by satishbkodali** [comment]
I see this too
![image](https://user-images.githubusercontent.com/22226388/145881928-af1c9c61-013c-4ccb-bef1-a7098375712b.png)

**Comment by purnang83** [comment]
We are also getting the same error with this version 2.13.0. Then we reverted back to apigeelint@2.12.0

steps:
  - script: 'npm install -g apigeelint@2.12.0'
    displayName: 'Run npm install apigeelint'

Error screenshot,

![Error](https://user-images.githubusercontent.com/51045519/145906979-602498d3-77df-47d3-a43a-ea8a73a1c8e7.JPG)

**Comment by ssvaidyanathan** [comment]
Fixed in v2.14.0
