### ISSUE TITLE
The policy type (SetOAuthV2Info) is not recognized

### ISSUE THREAD

**Issue by skylar-smith** [apigee/apigeelint#292]
After the 2.12.0 update policies that were valid are now showing as errors. They violate rule PO029. SetOAuthV2Info is a valid policy. I believe this is due to incomplete data in the following json file.

https://github.com/apigee/apigeelint/blob/master/lib/package/plugins/policyMetaData.json

**Comment by jmbreed** [comment]
Is there any news if this is being looked into?  I'm also getting the following linting error: "The policy type (SetOAuthV2Info) is not recognized".  I'm using Apigee linter version 2.12.0.

**Comment by ssvaidyanathan** [comment]
Fixed in v2.14.0
