### ISSUE TITLE
Receiving Error PO029 for ConnectorCallout policy

### ISSUE THREAD

**Issue by MatNascimento** [apigee/apigeelint#306]
Greetings.
First, I'd like to thank you for making ApigeeLint, it has been really useful for us.

As the issue, we are having a problem where Apigeelint is returning:
Message: The policy type (ConnectorCallout) is not recognized | Rule ID: PO029

This policy is necessary to use Apigee's Extensions.

https://docs.apigee.com/api-platform/reference/policies/extension-callout-policy
https://docs.apigee.com/api-platform/extensions/extensions-overview

We're using Apigeelint via NPM, version 2.20.0 (previous versions return the same error).

**Comment by ssvaidyanathan** [comment]
Its fixed in v2.21.0
Pls try

**Comment by MatNascimento** [comment]
It's working as expected
