### ISSUE TITLE
Apigeelint (2.25.0) is throwing an error for Hosted Target Proxy code analysis.

### ISSUE THREAD

**Issue by balaji-up** [apigee/apigeelint#330]
Hello,

We recently upgraded the Apigeelint version from v2.11.0 to v2.25.0, and now the apigeelint is throwing an error while validating the code for hosted target proxy as mentioned in the screenshot. As per apigee document `<HostedTarget />` should be in the `<TargetEndpoint/>` element, and there won't be target connection `<TargetConnection/>` element for this type proxy.

apigeelint - v2.25.0
node - v14.17.6
npm - v6.14.15

Can someone help to resolve issue or suggest if we are missing anything on the TargetEndpoint XML?

**Errors:**

![image](https://user-images.githubusercontent.com/4024788/186692433-db44d9dd-35cd-4b45-93c5-a9c54deebf06.png)

**Target Endpoint default XML:**

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TargetEndpoint name="default">
    <PreFlow name="PreFlow">
        <Request />
        <Response />
    </PreFlow>
    <Flows />
    <PostFlow name="PostFlow">
        <Request />
        <Response />
    </PostFlow>
    <HostedTarget />
</TargetEndpoint>`

Thanks,
Balaji Govindasamy

**Comment by ssvaidyanathan** [comment]
Fixed in v2.26.0

**Comment by balaji-up** [comment]
Hi @ssvaidyanathan 

The fixed version v2.26.0 still complaining about target endpoint default XML that `<TargetConnection/>` element is required, which is not required for hosted target based proxy.

Could you please resolve this issue?

**Errors:**

![image](https://user-images.githubusercontent.com/4024788/186884154-c5430f3d-117c-4088-a460-f5b6d28ebd94.png)

**Target Endpoint default XML:**

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TargetEndpoint name="default">
    <PreFlow name="PreFlow">
        <Request />
        <Response />
    </PreFlow>
    <Flows />
    <PostFlow name="PostFlow">
        <Request />
        <Response />
    </PostFlow>
    <HostedTarget />
</TargetEndpoint>`

Thanks,
Balaji Govindasamy
