### ISSUE TITLE
The apigeelint@v2.26.0 still throwing an error for hosted target based proxy

### ISSUE THREAD

**Issue by balaji-up** [apigee/apigeelint#331]
Hi @ssvaidyanathan 

The fixed version v2.26.0 still complaining about target endpoint default XML that `<TargetConnection/>` element is required, which is not required for hosted target based proxy.

Could you please resolve this issue?

**Errors:**

![image](https://user-images.githubusercontent.com/4024788/186884154-c5430f3d-117c-4088-a460-f5b6d28ebd94.png)

**Target Endpoint default XML:**

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TargetEndpoint name="default">
    <PreFlow name="PreFlow">
        <Request />
        <Response />
    </PreFlow>
    <Flows />
    <PostFlow name="PostFlow">
        <Request />
        <Response />
    </PostFlow>
    <HostedTarget />
</TargetEndpoint>`

Thanks,
Balaji Govindasamy

_Originally posted by @balaji-up in https://github.com/apigee/apigeelint/issues/330#issuecomment-1228328110_

**Comment by ssvaidyanathan** [comment]
Thanks for raising this @balaji-up 

This has some implications so its not a straight forward fix. We will work on it. For now, please add `<HTTPTargetConnection/>` if you can

**Comment by ssvaidyanathan** [comment]
Fixed in v2.27.0
Please try

**Comment by balaji-up** [comment]
Thank you, It's working now! 

I appreciate your help @ssvaidyanathan 👍
