### ISSUE TITLE
EP002 misplaced fault rules element error

### ISSUE THREAD

**Issue by k1mperial** [apigee/apigeelint#333]
this code https://github.com/apigee/apigeelint/blob/master/lib/package/plugins/EP002-misplacedElements.js

which was added recently conflicts with the behavior of another (open source) deployment tool we are using called apigeetool. i mean that it does not like having the fault rules inside of the step flow and throws the EP002 error but I found that apigeetool is autoformatting the flows in this way during deployment. i tried different orgs and i also tried deploying via terraform so im pretty sure this is an apigeetool issue. is it possible to only show it as a warning instead of an error because we use apigeelint in our pipeines and it fails whenever there's an error. thanks. 

<Step>
      <FaultRules/>
      <Name>RF-404</Name>
  </Step>

**Comment by ssvaidyanathan** [comment]
@k1mperial - can you share the apigeetool command you are using? And is this deployment to Apigee Edge/OPDK or Apigee X/hybrid?

**Comment by k1mperial** [comment]
@ssvaidyanathan i tested this using this command on Edge and in 2 different orgs, the behavior is the same

apigeetool deployproxy  -u myusername -o karenimperial-eval  -e test -n myproxyname -d .

**Comment by ssvaidyanathan** [comment]
Fix released in v2.28.0

**Comment by k1mperial** [comment]
thank you. can confirm error is gone.
