### ISSUE TITLE
apigee lint version 2.31 is breaking code quality check EP002 for shared flows

### ISSUE THREAD

**Issue by rinugdhanaraj** [apigee/apigeelint#348]
All shared flows are failing for the lint version 2.31 for the rule id EP002.

Steps listed below can be re-produced consistently

MAC:sf-guest-v1 $ apigeelint -V
2.31.0
MAC:sf-guest-v1 $ apigeelint -s /Users/XYZ/Downloads/sharedflowbundle/ -f table.js

/sharedflowbundle/sharedflows/default.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 3        │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 6        │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 10       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 14       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 18       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 21       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 26       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 30       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 33       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 36       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 39       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 42       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 45       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 49       │ 5        │ error    │ Invalid Step element                                   │ EP002                ║
║ 0        │ 0        │ warning  │ Missing HTTPProxyConnection.                           │ PD005                ║

/Users/XYZ/Downloads/sharedflowbundle/policies/DJWT.token.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 2        │ 69       │ warning  │ Non-standard name for policy (DJWT.token). Valid       │ PO007                ║
║          │          │          │ prefixes for the DecodeJWT policy:                     │                      ║
║          │          │          │ ["decodejwt","jwt"]. Valid patterns:                   │                      ║
║          │          │          │ ["^decodejwt$"].                                       │                      ║

/Users/XYZ/Downloads/sharedflowbundle/policies/GenJWT.generate-token.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 2        │ 72       │ warning  │ Non-standard name for policy                           │ PO007                ║
║          │          │          │ (GenJWT.generate-token). Valid prefixes for the        │                      ║
║          │          │          │ GenerateJWT policy: ["generatejwt","jwt","gjwt"].      │                      ║
║          │          │          │ Valid patterns: ["^generatejwt$"].                     │                      ║

╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 14 Errors                                                                                                      ║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 3 Warnings                                                                                                     ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

MAC:sf-guest-v1 $ apigeelint -s /Users/XYZ/Downloads/sharedflowbundle/ -f table.js -e EP002

/sharedflowbundle/sharedflows/default.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 0        │ 0        │ warning  │ Missing HTTPProxyConnection.                           │ PD005                ║

/Users/XYZ/Downloads/sharedflowbundle/policies/DJWT.token.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 2        │ 69       │ warning  │ Non-standard name for policy (DJWT.token). Valid       │ PO007                ║
║          │          │          │ prefixes for the DecodeJWT policy:                     │                      ║
║          │          │          │ ["decodejwt","jwt"]. Valid patterns:                   │                      ║
║          │          │          │ ["^decodejwt$"].                                       │                      ║

/Users/XYZ/Downloads/sharedflowbundle/policies/GenJWT.generate-token.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 2        │ 72       │ warning  │ Non-standard name for policy                           │ PO007                ║
║          │          │          │ (GenJWT.generate-token). Valid prefixes for the        │                      ║
║          │          │          │ GenerateJWT policy: ["generatejwt","jwt","gjwt"].      │                      ║
║          │          │          │ Valid patterns: ["^generatejwt$"].                     │                      ║

╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 0 Errors                                                                                                       ║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 3 Warnings                                                                                                     ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

**Comment by ssvaidyanathan** [comment]
@rinugdhanaraj - I think its working as expected. There was a recent bug [fixed](https://github.com/apigee/apigeelint/pull/344) and released as part of 2.31.0

The warnings you see are working as expected. If you assign the following prefix for those policies, those warnings should go. 

For the EP002 errors, we can check if you can provide the contents of `/sharedflowbundle/sharedflows/default.xml`.

**Comment by rinugdhanaraj** [comment]
@ssvaidyanathan Thanks for taking a look.

The issue here is the shared flow (not specific to one) fails here on ApigeeLint Version 2.31.0 
/sharedflowbundle/sharedflows/default.xml
49 │ 5 │ error │ Invalid Step element │ EP002 ║

and the same sharedflow with Apigeelint version 2.
[sf-test-apigeelint-v1_rev2_2022_09_30.zip](https://github.com/apigee/apigeelint/files/9686320/sf-test-apigeelint-v1_rev2_2022_09_30.zip)
1.0 will not report this error.

I am attaching a dummy sharedflow with just one step and you will see on error related to EP002. The more the steps we have in the sharedflow we will have the corresponding no.of errors

 Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼───────────────────────
║ 3        │ 5        │ error    │ Invalid Step element                                   │ EP002                ║

**Comment by ssvaidyanathan** [comment]
Let me take a look. Thanks for the zip
