### ISSUE TITLE
Apigeelint scan Faling for Apigee proxy with an error The policy type (SetIntegrationRequest) is not available in the profile apigee. 

### ISSUE THREAD

**Issue by kondurure** [apigee/apigeelint#363]
Apigeelint scan Faling for Apigee proxy with an error The policy type (SetIntegrationRequest) is not available in the profile apigee. 

/home/runner/work/api-proxy.hl-invokeFulfilment-api/api-proxy.hl-invokeFulfilment-api/apiproxy/policies/SIR-CsDsConversionIntegration.xml

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 0        │ 0        │ error    │ The policy type (SetIntegrationRequest) is not         │ PO028                ║
║          │          │          │ available in the profile apigee.                       │                      ║

**Comment by ssvaidyanathan** [comment]
You need to run the apigeelint command with `--profile=apigeex` whenever you run it
Closing this issue

**Comment by kondurure** [comment]
Thanks @ssvaidyanathan
