### ISSUE TITLE
Resource filePath is file name only

### ISSUE THREAD

**Issue by astellingwerf** [apigee/apigeelint#370]
For the report to be truly useful for Resources, their location should be exposed, just like for Policies. With the full path, code quality reports can be generated for the source code, whereas with just a filename, fuzzy logic needs to be implemented to reconstruct the path.

Work was done for this with #353, but for Resources the `fname` is used instead of the `path`.

**Comment by ssvaidyanathan** [comment]
@astellingwerf - thanks for flagging this
I have pushed a fix. Can you please check with v2.39.0?

**Comment by astellingwerf** [comment]
Work for my (admittedly limited) use case. Thanks @ssvaidyanathan!
