### ISSUE TITLE
ST003 | Apigeelint is appending `.content` to the source variable, even though the variable already includes the .content suffix

### ISSUE THREAD

**Issue by prashantrahate** [apigee/apigeelint#378]
Apigeelint is appending .content to the source variable, even though the variable already includes the .content suffix in its name (tokenResponse.content).
Policy:
![image](https://github.com/apigee/apigeelint/assets/17001471/88c81593-97f7-4e11-81f2-8f1ba78548bc)
Apigeelint Result:
![image](https://github.com/apigee/apigeelint/assets/17001471/aa2a4b5b-0012-48e6-86da-9967b87c84e7)

As a result, proxy linter is producing an error message that appends `.content` twice.

When the source variable is changed to `tokenResponse`, the error message from Apigeelint is displayed correctly.
![image](https://github.com/apigee/apigeelint/assets/17001471/3e188a52-0c19-4a17-9172-502da10d51c5)

Is it possible to fix this issue by adding the suffix ".content" only when it is not already provided in the source?

**Comment by ssvaidyanathan** [comment]
@prashantrahate - I think its working as expected. What the tool does - is its using the variable you use in the `<Source>` attribute and recommends to add that to the `<Condition>`

You do not need to add `.content` in the `<Source>` configuration. You just need to put `tokenResponse`. You can refer to [this link](https://cloud.google.com/apigee/docs/api-platform/reference/policies/extract-variables-policy#sourceelement).

Please update your ExtractVariables policy to just have the variable (excluding the `.content`) and then it should work as expected. The `.content` is required for the `<Condition>` tag, hence the tool suggest you add that to the variable.

**Comment by prashantrahate** [comment]
Got it, Thanks you @ssvaidyanathan.
