### ISSUE TITLE
PO026 incorrectly flags correct AssignVariable tample as incorrect

### ISSUE THREAD

**Issue by LukaszGrochal** [apigee/apigeelint#387]
Problem is that correctly assigned variable is tagged as incorrect.  It looks like issue is with curly brackets.
As an error I got:
║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 17       │ 17       │ error    │ undefined                                              │ PO026 
`    
   <AssignVariable>
      <Name>timeStamp</Name>
      <Template>{timeFormatUTCMs('yyyy-MM-dd HH-mm-ss',system.timestamp)} UTC</Template>
    </AssignVariable>
`

the whole policy looks like that and on beginning of the month it was working correctly:
`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>  
<RaiseFault async="false" continueOnError="false" enabled="true" name="RF-Authorization">    
  <IgnoreUnresolvedVariables>true</IgnoreUnresolvedVariables>
  
  <FaultResponse>  
    
    <AssignVariable>
      <Name>errorId</Name><Template>{createUuid()}</Template>
    </AssignVariable>  
    
    <AssignVariable>
      <Name>code</Name><Value>401</Value>
    </AssignVariable>  
    
    <AssignVariable>
      <Name>timeStamp</Name>
      <Template>{timeFormatUTCMs('yyyy-MM-dd HH-mm-ss',system.timestamp)} UTC</Template>
    </AssignVariable>
    <Set>    
      <Payload contentType="application/json">UNAUTHORIZED</Payload><StatusCode>401</StatusCode><ReasonPhrase>UNAUTHORIZED</ReasonPhrase>
    </Set>
  </FaultResponse>
</RaiseFault>

`

**Comment by ssvaidyanathan** [comment]
@LukaszGrochal - which version are you using?

**Comment by LukaszGrochal** [comment]
I think I am using the latest.
Before each use I am installing it with 
`npm install -g apigeelint`

**Comment by ssvaidyanathan** [comment]
Can you try with the latest version we just pushed v2.43.0? Pls reopen if the issue still exist
