### ISSUE TITLE
PO028 - The policy type (CORS) is not available in the profile apigee - Apigee X

### ISSUE THREAD

**Issue by kiranjyoth** [apigee/apigeelint#394]
Hello team, Encountering error with CORS policy, triggering RuleID PO028

**Details**
apigeelint version
2.44.0

Related to - #335  #336 

Thanks!

**Comment by kiranjyoth** [comment]
@ssvaidyanathan yes, the proxy is being deployed to Apigee X, but the policy is not being identified.

**Comment by ssvaidyanathan** [comment]
@kiranjyoth - you need to run the apigeelint command with `--profile apigeex`

**Comment by kiranjyoth** [comment]
Thanks @ssvaidyanathan I will update the script and test. Will close this issue and mark as resolved once validated. Thank you for you quick response!

**Comment by ssvaidyanathan** [comment]
@kiranjyoth - can this be closed?

**Comment by kiranjyoth** [comment]
Yes @ssvaidyanathan, closing this issue. using profile switch worked perfectly!
