### ISSUE TITLE
BN001 not flagging js resources in resources folder

### ISSUE THREAD

**Issue by gislikonrad** [apigee/apigeelint#404]
When analyzing the structure of an apiproxy or sharedflow bundle, the linter is not flagging a structure like this

    .
    ├── ...
    ├── resources                    
    │   ├── incorrect_location.js          # This location should be flagged in the bn001 rule
    │   ├── jsc                 
    │   │   └──  correct_location.js                
    └── ...

When uploading  a bundle that has this structure (to apigee hybrid), this causes the upload to fail with a bad bundle format error.

**Comment by ssvaidyanathan** [comment]
Thanks - I have added test case for your fix. Its released in v2.46.0

**Comment by gislikonrad** [comment]
The npm install of 2.46.0 is failing, just fyi...
<img width="916" alt="image" src="https://github.com/apigee/apigeelint/assets/1843528/f8d1eb04-4cd6-4776-9e8e-75a17789476e">

Looks like it can't find peggy.js.
