### ISSUE TITLE
ApigeeLint should not error for authentication element in TragetServer

### ISSUE THREAD

**Issue by priyanka212** [apigee/apigeelint#419]
I need to understand why ApigeeLint gives error for Authentication tag in target server. I'm using APIGEEX for developing proxy. I use this tag to generate Google access token.

@ssvaidyanathan @DinoChiesa

**Comment by ssvaidyanathan** [comment]
@priyanka212 - can you please share the code snippet of your TargetEndpoint

Also the apigeelint command you are running?

**Comment by ssvaidyanathan** [comment]
I saw your community post - can you confirm you are passing `--profile apigeex` in your apigeelint command?
