### ISSUE TITLE
PO034, for AssignMessage hygiene is using the incorrect XML element 

### ISSUE THREAD

**Issue by DinoChiesa** [apigee/apigeelint#439]
Both the plugin and the policy tests need to change.  Should add tests for a full bundle, to avoid such problems in the future.

**Comment by DinoChiesa** [comment]
Either i misunderstood the problem, or... I still need to re-discover the problem I was referencing here. I'm going to keep this open for a while , pending further investigation.

**Comment by k1mperial** [comment]
@DinoChiesa
we are now getting this error on apigeelint version 2.55.2 whereas it was not throwing this error in version 2.45.0:

element <FaultRules> is not allowed here - PO034

we use the apigeetool CLI to deploy proxies over the pipeline and while doing some tests, found that during deployment apigeetool automatically adds this line to assign message policies

<FaultRules/>

and so this update on apigeelint flagging this as an error is in conflict with apigeetool's behavior

**Comment by DinoChiesa** [comment]
@k1mperial - 
Definitely apigeetool is inserting random elements. That element is not actually supported within AssignMessage.  I think you should raise a bug with apigeetool, or whatever tool (or person!) is generating the AssignMessage policy.

**Comment by DinoChiesa** [comment]
I'm closing this because I lost the plot.
