### ISSUE TITLE
apigeelint errors/warnings not showing in Gitlab CodeQuality tab

### ISSUE THREAD

**Issue by spjohn85** [apigee/apigeelint#450]
I am integrating apigeelint in Gitlab Pipeline and followed the steps given in README, but I am not able to see the report in CodeQuality tab. 

1. Warnings are not being displayed (if there are no errors)
2. Even errors when exist and is failing the pipeline, but on Code Quality it shows as below, 

[apigeelint-results.json](https://github.com/user-attachments/files/15972889/apigeelint-results.json)

![image](https://github.com/apigee/apigeelint/assets/36644947/7cf89381-c3a7-42cd-ac19-a84618e9be51)

Any thoughts on how to get this done ?

**Comment by ssvaidyanathan** [comment]
@spjohn85 - am no GitLab expert. Is there a particular format the output should be for apigeelint? Apigeelint supports html too. You can run `apigeelint .... -f html.js`

and push that to your pipeline to use

**Comment by spjohn85** [comment]
@ssvaidyanathan - Looks like Gitlab requires output in a specific format. Could this be supported ? 

https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool

**Comment by spjohn85** [comment]
Looks like its supported `-f codeclimate` helps

**Comment by ssvaidyanathan** [comment]
Thats good to know.. Didnt know that format would work..
