### ISSUE TITLE
RevokeOauthV2 is available in apigee edge as well but fails in linting with apigee profile

### ISSUE THREAD

**Issue by globalpayments-vinsharma** [apigee/apigeelint#473]
While working recently it was noticed that apigee edge also has featured the RevokeOauthV2 policy. The same seems to be failing in Apigee Lint with PO028 stating policy not available in profile. Could you please enable this for both the profiles so that the linting error can be resolved.

Link to file: https://github.com/apigee/apigeelint/blob/5715504583490b3d0c02c5d13d394e99e8340105/lib/package/plugins/policyMetaData.json#L51

**Comment by ssvaidyanathan** [comment]
@globalpayments-vinsharma - Thanks for bringing this to our attention

The patch fix is released  as `v2.56.2`

Please update your version and it should have the fix

**Comment by globalpayments-vinsharma** [comment]
Thanks for the quick fix
