### ISSUE TITLE
new plugin: for Quota policy, if CountOnly found, should also have EnforceOnly

### ISSUE THREAD

**Issue by DinoChiesa** [apigee/apigeelint#475]
It should be the case that if there is an EnforceOnly Quota policy, we should also have a CountOnly policy attached. 

@ssvaidyanathan @kurtkanaskie WDYT?    Are there cases where it makes sense to violate this? For example, a CountOnly policy in a FlowHook-attached sharedflow, and an EnforceOnly policy directly attached in the proxy?

**Comment by kurtkanaskie** [comment]
I've always used them in pairs. EnforceOnly doesn't increment the count so it's not useful on its own.
I suppose they could be in different shared flows (e.g. PreFlow flow hook and PostFlow flow hook).

**Comment by ssvaidyanathan** [comment]
> I've always used them in pairs. EnforceOnly doesn't increment the count so it's not useful on its own. I suppose they could be in different shared flows (e.g. PreFlow flow hook and PostFlow flow hook).

Yes - thats how its been used, if they want it in two different sharedflows. Sometimes in request vs response flows as well
