### ISSUE TITLE
BN013 is not preserving path correctly

### ISSUE THREAD

**Issue by DanielGlos** [apigee/apigeelint#482]
We have a folder structure that is like this:
apiproxy
- policies
- proxies
- resources
    - jsc
        - responses
            - JS-SomeFile.js

So the JS file sits under \apiproxy\resources\jsc\responses
This file is correctly used in policy like
`<IncludeURL>jsc://responses/JS-SomeFile.js</IncludeURL>`

But the linter is giving error:
Unreferenced resource jsc/JS-SomeFile.js. There are no policies that reference this resource.

File mentioned in the error jsc/JS-SomeFile.js doesn't even exist. Somehow the paths are not respected.

**Comment by DinoChiesa** [comment]
Thanks for reporting this.

**Comment by ssvaidyanathan** [comment]
This is fixed and released in v2.59.0
