### ISSUE TITLE
New Plugin - Storing data greater than 512kb size in cache

### ISSUE THREAD

**Issue by davidwallen** [apigee/apigeelint#65]
When data > 512kb is cached, the consequences are as follows :
API requests executed for the first time on each of the Message Processors need to get the data independently from the original source (policy or a target server), as entries > 512kb are not available in L2 cache.
Storing larger data (> 512kb) in L1 cache tends to put more stress on the platform resources.  It results in the L1 cache memory being filled up faster and hence lesser space being available for other data.  As a consequence, one will not be able to cache the data as aggressively as one would like to.
Cached entries from the Message Processors will be removed when the limit on the number of entries is reached. This causes the data to be fetched from the original source again on the respective Message Processors.

It is preferred to store data of size < 512kb in cache to get optimum performance. 
If there’s a need to store data > 512kb, then consider
Apigee BaaS for caching/storing large data or
Compressing the data (if feasible) and store the data only if the compressed size <= 512kb.

**Comment by DinoChiesa** [comment]
The static analysis tool will not be able to know the size of the data being handled at runtime. This information isn't knowable during the static analysis phase. This can be covered by a runtime check, only.
