### ISSUE TITLE
Detect context vs content in JS

### ISSUE THREAD

**Issue by seantdg** [apigee/apigeelint#79]
On a Dev Bootcamp, we realised it would be nice to detect for a spelling mistake in the word 'context'. It is very common to accidentally write content.setVariable...
This may be something that can be captured as part of the JSLint/ESLint implementation, but I thought it would make sense to document this requirement here before we forget...

:)

**Comment by DinoChiesa** [comment]
Yes, this is a job for the jshint plugin, which is embedded in PO013.  Or you could use and configure the eslint plugin for the same purpose. That is implemented in PO025. 

Either of those tools is a configurable linter for JavaScript. Supposing you want to use JSHint, then with this kind of jshint setting in the file: 
```
/* global context:true */
/* jshint strict:implied */

```

...the PO013 plugin will emit a warning like this: 
```
 {
    "filePath": "/apiproxy/resources/jsc/applyFieldFilter.js",
    "errorCount": 0,
    "warningCount": 1,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "messages": [
      {
        "severity": 1,
        "source": "        content.setVariable('something', 'a-value');",
        "line": 46,
        "column": 9,
        "message": "warning W117: 'content' is not defined.",
        "ruleId": "PO013",
        "nodeType": "Resource"
      }
    ]
  },
```

You could also externalize the jshint configuration into a file named `.jshintrc`, placed in the parent directory of the APIProxy. If you use that route, then the file content might look like this for an Apigee JS callout: 
```
{
  "strict": "implied",
  "esversion": 6,
  "globals" : { "context" : true, "properties" : true, "crypto" : true, "httpClient": true }
}
```

This configuration tells the jshint tool to lint the code assuming ESVersion 6 compliance, and "strict: implied" tells jshint to flag  any implicit global variable reference. This config also specifies some global variables that the Apigee JS callout can use: context, properties, and so on.
